#ifndef HEADER_EMPIRICAL_INFO_H_INCLUDED
#define HEADER_EMPIRICAL_INFO_H_INCLUDED

/* #undef VERSION_MAJOR */
/* #undef VERSION_MINOR */
/* #undef VERSION_TYPE */
/* #undef VERSION_BUILD */
/* #undef VERSION_STRING */

#endif // HEADER_EMPIRICAL_INFO_H_INCLUDED
